### ISSUE TITLE
Whether requirements can be provided?

### ISSUE THREAD

**Issue by tttingyu** [jinhojsk515/ALBEF_tutorial#1]
Hi, thank you for your providing the wonderful paper code, may I ask if you can provide the requirements.txt for this code.

Hoping for your reply. Thanks a lot !

**Comment by jinhojsk515** [comment]
requirements.txt attached. I hope it works!

torch>=1.9.0
torchvision>=0.10.0
Pillow>=9.0.1
transformers>=4.18.0
tqdm>=4.62.3
numpy>=1.21.5
sklearn>=0.0
timm>=0.5.4
